name: Python Package Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build wheel
    - name: Verify package can be built
      run: |
        # Just verify that the package can be built, don't run tests
        python -m build --sdist --wheel
        echo "Package built successfully!"